config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: "",
    path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
    controllers: { registrations: 'registrations' }

  root to: 'home#index'
  get  'about',   to: 'home#about'
  get 'bad_request' => 'home#bad_request'
  get 'forbidden' => 'home#forbidden'
  get 'internal_server_error' => 'home#internal_server_error'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index]
    resources :purchases, only: [:index]
    resources :unpurchases, only: [:index]
    get :following, :followers, on: :member
  end

  resources :posts do
    get "search", on: :collection
    patch "like", "unlike", on: :member, controller: :likes
    get "liked", on: :collection, controller: :likes
    get "liker", on: :member, controller: :likes
    get "timeline", on: :collection
  end
  resources :purchases, only: [:index]
  resources :unpurchases, only: [:index]
  resources :relationships, only: [:create, :destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :post_id, presence: true
  validates :user_id, presence: true

  validate do
    unless user && user.likeable_for?(post)
      errors.add(:base, :invalid)
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, except: [:liker]

  def like
    @post = Post.find(params[:id])
    if @post.published == true
      current_user.liked_posts << @post
      respond_to do |format|
        format.html { request.referrer || root_url }
        format.js
      end
    end
  end

  def unlike
    @post = Post.find(params[:id])
    if @post.published == true
      current_user.liked_posts.destroy(@post)
      respond_to do |format|
        format.html { request.referrer || root_url }
        format.js
      end
    end
  end

  def liked
    @posts = current_user.liked_posts.published.order("likes.created_at DESC").page(params[:page]).per(10)
  end

  def liker
    @post = Post.published.find_by(id: params[:id])
    if @post
      @users = @post.likers.order("likes.created_at DESC").page(params[:page]).per(10)
    end
  end
end

app/views/likes/_like.html.erb
<span id="like_form-<%= post.id %>">
  <% if current_user && current_user.likeable_for?(post) %>
    <%= link_to "★", like_post_path(post.id), method: :patch, remote: true, class: "liked" %>
  <% elsif current_user && post.likers.find_by(id: current_user.id) %>
    <%= link_to "★", unlike_post_path(post.id), method: :patch, remote: true, class: "unliked" %>
  <% else %>
    ★
  <% end %>
  <%= link_to "#{post.likes.count}", liker_post_path(post.id) %>
</span>

app/views/likes/like.js.erb
$("#like_form-<%= @post.id %>").html("<%= escape_javascript(render partial: 'like', locals: { post: @post }) %>");

app/views/likes/liked.html.erb
<% provide(:title, "#{current_user.name}さんのいいね一覧") %>

<div class="container-fluid">
  <h3><%= "#{current_user.name}さんのいいね一覧" %></h3>

  <% if @posts.present? %>
    <p>
      <span class="green" style="color:#abd700;">緑:未購入</span><br>
      <span class="red" style="color:#ffab6b;">赤:購入済</span>
    </p>
  <% end %>

  <%= render 'shared/posts', posts: @posts %>
</div>

app/views/likes/liker.html.erb
<% provide(:title, "#{@post.name}にいいねしたユーザー") %>

<div class="container-fluid">
  <h3><%= "' #{@post.name} 'にいいねしたユーザー" %></h3>

  <%= paginate @users %>
  <% @users.each do |user| %>
    <div class="list-group">
      <li class="list-group-item">
        <h3>
          <%= gravatar_for(user, size: 50) %>
          <%= link_to user.name, user_path(user) %>
        </h3>
        <% if user.bio %>
          <p class="lead">
            <%= truncate user.bio %>
            <% if user.bio.size > 30 %>
              <%= link_to "もっと読む", user_path(user) %>
            <% end %>
          </p>
        <% end %>
      </li>
    </div>
  <% end %>
  <%= paginate @users %>
</div>

app/views/likes/unlike.js.erb
$("#like_form-<%= @post.id %>").html("<%= escape_javascript(render partial: 'like', locals: { post: @post }) %>");