config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: "",
    path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
    controllers: { registrations: 'registrations' }

  root to: 'home#index'
  get  'about',   to: 'home#about'
  get 'bad_request' => 'home#bad_request'
  get 'forbidden' => 'home#forbidden'
  get 'internal_server_error' => 'home#internal_server_error'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index]
    resources :purchases, only: [:index]
    resources :unpurchases, only: [:index]
    get :following, :followers, on: :member
  end

  resources :posts do
    get "search", on: :collection
    patch "like", "unlike", on: :member, controller: :likes
    get "liked", on: :collection, controller: :likes
    get "liker", on: :member, controller: :likes
    get "timeline", on: :collection
  end
  resources :purchases, only: [:index]
  resources :unpurchases, only: [:index]
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary w-100" %>
<% end %>

app/views/shared/_follow_form.html.erb
<% if user_signed_in? %>
  <% @user ||= current_user %>
  <% if current_user != @user %>
    <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'shared/unfollow' %>
    <% else %>
      <%= render 'shared/follow' %>
    <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to(root_path,class: "navbar-brand") do %>Home<% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to(about_path, class: "nav-link") do %>About<% end %>
      </li>
      <li class="nav-item active">
        <%= link_to(users_path, class: "nav-link") do %>ユーザー一覧<% end %>
      </li>
      <li class="nav-item active">
        <%= link_to(posts_path, class: "nav-link") do %>公開投稿一覧<% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to(new_post_path, class: "nav-link") do %>投稿する<% end %>
        </li>
        <li class="nav-item active">
          <%= link_to(user_path(current_user), class: "nav-link") do %><%= current_user.name %>さん<% end %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">アカウント</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <%= link_to(user_posts_path(current_user), class: "dropdown-item") do %>投稿一覧<% end %>
            <%= link_to(user_unpurchases_path(current_user), class: "dropdown-item") do %>未購入一覧<% end %>
            <%= link_to(user_purchases_path(current_user), class: "dropdown-item") do %>購入済一覧<% end %>
            <%= link_to(liked_posts_path, class: "dropdown-item likes") do %>いいね一覧<% end %>
            <%= link_to(timeline_posts_path, class: "dropdown-item timeline") do %>タイムライン<% end %>
            <%= link_to(edit_user_registration_path, class: "dropdown-item") do %>プロフィール変更・退会<% end %>
            <%= link_to(destroy_user_session_path, method: :delete, class: "dropdown-item log-out") do %>ログアウト<% end %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to(new_user_registration_path, class: "nav-link") do %>新規登録<% end %>
        </li>
        <li class="nav-item active">
          <%= link_to(new_user_session_path, class: "nav-link") do %>ログイン<% end %>
        </li>
      <% end %>
    </ul>
    <%= form_tag :search_posts, method: :get, class: "search form-inline my-2 my-lg-0" do %>
      <%= text_field_tag "q", params[:q], class: "form-control mr-sm-2", placeholder: "投稿を検索" %>
      <%= submit_tag "検索", class: "btn btn-secondary my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/shared/_post.html.erb
<%= link_to gravatar_for(post.user, size: 50), post.user %>
<% if params[:user_id].present? %>
  <span class="user">
    <%= post.user.name %>
  </span>
<% elsif current_user == post.user %>
  <span class="user">
    <%= link_to "#{post.user.name} (投稿一覧へ)", user_posts_path(post.user) %>
  </span>
<% else %>
  <span class="user">
    <%= link_to "#{post.user.name} (公開投稿一覧へ)", user_posts_path(post.user) %>
  </span>
<% end %>
<span class="post"><%= link_to post.name, post_path(post) %></span>
<span class="published">
  <% if post.published == false %>
    公開設定：非公開
  <% else %>
    公開設定：公開
  <% end %>
</span>
<span class="timestamp">
  投稿時間：<%= time_ago_in_words(post.created_at) %>前
  <% if current_user == post.user %>
    <%= link_to "削除", post_path(post), method: :delete,
                                     data: { confirm: "You sure?" } %>
  <% end %>
</span>
<span id="like-<%= post.id %>" class="like">
  <%= render 'likes/like', post: post %>
</span>
<span class="picture">
  <%= image_tag post.picture.url if post.picture? %>
</span>

app/views/shared/_posts.html.erb
<div class="posts">
  <%= paginate posts %>
  <% if posts.present? %>
    <% posts.each do |post| %>
      <div class="list-group">
        <li class="list-group-item">
          <% if post.purchased == false %>
            <div class="unpurchased">
              <%= render 'shared/post', post: post %>
            </div>
          <% else %>
            <div class="purchased">
              <%= render 'shared/post', post: post %>
            </div>
          <% end %>
        </li>
      </div>
    <% end %>
  <% else %>
    <h3>投稿がありません</h3>
  <% end %>
  <%= paginate posts %>
</div>

app/views/shared/_stats.html.erb
<% if user_signed_in? %>
  <% @user ||= current_user %>
  <div class="stats">
    <a href="<%= following_user_path(@user) %>">
      <strong id="following" class="stat">
        <%= @user.following.count %>
      </strong>
      フォロー
    </a>
    <a href="<%= followers_user_path(@user) %>">
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
      フォロワー
    </a>
  </div>
<% end %>

app/views/shared/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-secondary w-100" %>
<% end %>