config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: "",
    path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
    controllers: { registrations: 'registrations' }

  root to: 'home#index'
  get  'about',   to: 'home#about'
  get 'bad_request' => 'home#bad_request'
  get 'forbidden' => 'home#forbidden'
  get 'internal_server_error' => 'home#internal_server_error'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index]
    resources :purchases, only: [:index]
    resources :unpurchases, only: [:index]
    get :following, :followers, on: :member
  end

  resources :posts do
    get "search", on: :collection
    patch "like", "unlike", on: :member, controller: :likes
    get "liked", on: :collection, controller: :likes
    get "liker", on: :member, controller: :likes
    get "timeline", on: :collection
  end
  resources :purchases, only: [:index]
  resources :unpurchases, only: [:index]
  resources :relationships, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  mount_uploader :picture, PictureUploader
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 500 }
  validates :user_id, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :purchased, :published, inclusion: { in: [true, false] }
  validate :purchased_error
  validate :purchased_at_check
  validate :picture_size

  # 公開ポスト
  scope :published, -> { where(published: true) }
  # 任意のユーザーのポストと公開ポスト
  scope :full, ->(user) { where("user_id = ?", user.id).or(published) }

  # 投稿の中に任意のユーザーによる投稿がある場合はそのユーザーのポストと公開ポスト、ない場合は公開ポスト
  scope :readable_for, ->(user) { user ? full(user) : published }

  scope :purchased, -> { where(purchased: true) }
  scope :unpurchased, -> { where(purchased: false) }

  def self.search(query)
    return Post.all unless query
    Post.where(['name LIKE ?', "%#{query}%"])
  end

  private

  # 購入日が存在するならば、購入状態は購入済にする
  def purchased_error
    if purchased_at.present? && purchased == false
      errors.add(:purchased_at, "が入力されています。購入済を選択してください。")
    end
  end

  # 購入日が現在よりも後にならないようにする
  def purchased_at_check
    return if date_valid? || purchased_at.blank?
    errors.add(:purchased_at, "は本日以前にしてください") unless purchased_at <= Date.today
  end

  # 存在しない日付をチェックする
  def date_valid?
    date = purchased_at_before_type_cast
    return if date.blank? || date[1].blank? || date[2].blank? || date[3].blank?
    y = date[1]
    m = date[2]
    d = date[3]
    unless Date.valid_date?(y, m, d)
      errors.add(:purchased_at, "の値が不正です")
    end
  end

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "は5MB未満にしてください")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @posts = @user.posts.readable_for(current_user).order(created_at: :desc).page(params[:page]).per(10)
    else
      @posts = Post.published.order(created_at: :desc).page(params[:page]).per(10)
    end
  end

  def show
    @post = Post.readable_for(current_user).find_by(id: params[:id])
    if @post
      render 'show'
    else
      render 'errors/not_found_or_unpublished'
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to user_posts_path(current_user), notice: "投稿を作成しました。"
    else
      render "new"
    end
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to user_posts_path(current_user), notice: "投稿内容を更新しました。"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to request.referrer || root_url, notice: "投稿を削除しました。"
  end

  def search
    @posts = Post.readable_for(current_user).search(params[:q]).order(created_at: "DESC").page(params[:page]).per(10)
  end

  def timeline
    @feed_items = current_user.feed.full(current_user).order(created_at: "DESC").page(params[:page]).per(10)
  end

  private

  def post_params
    params.require(:post).permit(:name, :description, :price,
                                 :purchased, :purchased_at, :published, :picture)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to(root_url) if @post.nil?
  end
end

app/views/posts/edit.html.erb
<% provide(:title, "投稿内容編集") %>

<div class="container-fluid">
  <h4>投稿内容編集</h4>
  <%= form_for(@post) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name, "商品名 (必須)" %>
    <%= f.text_field :name, class: "form-control" %><br />

    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %><br />

    <%= f.label :price, "値段 (円)" %>
    <%= f.number_field :price, class: "form-control" %><br />

    <p>購入状態</p>
    <div class="card">
      <div class="card-body">
        <div class="form-check form-check-inline">
          <%= f.radio_button :purchased, false, class: "form-check-input", type: "checkbox", id: "unpurchased" %>
          <%= f.label :unpurchased, for: "purchased_2", class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :purchased, true, class: "form-check-input", type: "checkbox", id: "purchased" %>
          <%= f.label :purchased, for: "purchased_1", class: "form-check-label" %>
        </div>
      </div>
    </div><br />

    <div id="purchased_at">
      <%= f.label :purchased_at, for: "post_purchased_at_1i" %><br />
      <div class="card">
        <div class="card-body">
          <%= f.date_select :purchased_at,
                    start_year: Time.current.year, end_year: 2000,
                    include_blank: true,
                    use_month_numbers: true %>
        </div>
      </div>
    </div><br />

    <p>公開設定</p>
    <div class="card">
      <div class="card-body">
        <div class="form-check form-check-inline">
          <%= f.radio_button :published, false, class: "form-check-input", type: "checkbox" %>
          <%= f.label :unpublished, for: "published_2", class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :published, true, class: "form-check-input", type: "checkbox" %>
          <%= f.label :published, for: "published_1", class: "form-check-label" %>
        </div>
      </div>
    </div><br /><br />

    <p>画像を投稿</p>
    <div class="card">
      <div class="card-body">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </div>
    </div><br /><br />

    <div class="actions">
      <%= f.submit "更新", class: "btn btn-primary w-100", size: 50 %>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  var rb_purchased = $("#purchased");
  var rb_unpurchased = $("#unpurchased");
  var field = $("#purchased_at");

  console.log(field);

  var changePurchasedAt = function() {
    if (rb_purchased.prop("checked"))
      field.show()
    else
      field.hide()
  }

  var changeUnpurchasedAt = function() {
    if (rb_unpurchased.prop("checked"))
      field.hide()
    else
      field.show()
  }

  rb_purchased.bind("click", changePurchasedAt);
  rb_unpurchased.bind("click", changeUnpurchasedAt);

  changePurchasedAt();
  changeUnpurchasedAt();
</script>

<script type="text/javascript">
  $('#post_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('5MBより小さいファイルを選択してください');
    }
  });
</script>

app/views/posts/index.html.erb
<% @user? provide(:title, "#{@user.name}さんの投稿一覧") : provide(:title, "投稿一覧") %>

<div class="container-fluid">
  <% if params[:user_id].present? %>
    <% if current_user == @user %>
      <h3><%= "#{@user.name}さんの投稿一覧" %></h3>
    <% else %>
      <h3><%= "#{@user.name}さんの投稿一覧(公開用)" %></h3>
    <% end %>
  <% else %>
    <h3>公開投稿一覧</h3>
  <% end %>
  
  <% if params[:user_id].present? %>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  <% end %>

  <% if @posts.present? %>
    <p>
      <span class="green" style="color:#abd700;">緑:未購入</span><br>
      <span class="red" style="color:#ffab6b;">赤:購入済</span>
    </p>
  <% end %>

  <% if user_signed_in? %>
    <%= link_to "新規投稿を作成", new_post_path, class: "btn btn-lg btn-primary" %>
  <% end %>

  <% if params[:user_id].present? %>
    <% if current_user == @user %>
      <div><%= link_to "#{@user.name}さんの未購入一覧へ", user_unpurchases_path(@user) %></div>
      <div><%= link_to "#{@user.name}さんの購入済一覧へ", user_purchases_path(@user) %></div><br />
    <% else %>
      <div><%= link_to "#{@user.name}さんの未購入一覧へ(公開用)", user_unpurchases_path(@user) %></div>
      <div><%= link_to "#{@user.name}さんの購入済一覧へ(公開用)", user_purchases_path(@user) %></div><br />
    <% end %>
  <% else %>
    <div><%= link_to "未購入一覧へ", unpurchases_path %></div>
    <div><%= link_to "購入済一覧へ", purchases_path %></div><br />
  <% end %>

  <%= render 'shared/follow_form' if user_signed_in? %>

  <%= render 'shared/posts', posts: @posts %>
</div>

app/views/posts/new.html.erb
<% provide(:title, "新規作成") %>

<div class="container-fluid">
  <h4>新規作成</h4>
  <%= form_for(@post) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name, "商品名 (必須)" %>
    <%= f.text_field :name, class: "form-control" %><br />

    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %><br />

    <%= f.label :price, "値段 (円)" %>
    <%= f.number_field :price, class: "form-control" %><br />

    <p>購入状態</p>
    <div class="card">
      <div class="card-body">
        <div class="form-check form-check-inline">
          <%= f.radio_button :purchased, false, class: "form-check-input", type: "checkbox", id: "unpurchased" %>
          <%= f.label :unpurchased, for: "purchased_2", class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :purchased, true, class: "form-check-input", type: "checkbox", id: "purchased" %>
          <%= f.label :purchased, for: "purchased_1", class: "form-check-label" %>
        </div>
      </div>
    </div><br />

    <div id="purchased_at">
      <%= f.label :purchased_at, for: "post_purchased_at_1i" %><br />
      <div class="card">
        <div class="card-body">
          <%= f.date_select :purchased_at,
                    start_year: Time.current.year, end_year: 2000,
                    include_blank: true,
                    use_month_numbers: true %>
        </div>
      </div>
    </div><br />

    <p>公開設定</p>
    <div class="card">
      <div class="card-body">
        <div class="form-check form-check-inline">
          <%= f.radio_button :published, false, class: "form-check-input", type: "checkbox", id: "unpublished" %>
          <%= f.label :unpublished, for: "published_2", class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :published, true, class: "form-check-input", type: "checkbox", id: "published" %>
          <%= f.label :published, for: "published_1", class: "form-check-label" %>
        </div>
      </div>
    </div><br /><br />

    <p>画像を投稿</p>
    <div class="card">
      <div class="card-body">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </div>
    </div><br /><br />

    <div class="actions">
      <%= f.submit "投稿", class: "btn btn-primary w-100", size: 50 %>
    </div><br />
  <% end %>
</div>

<script type="text/javascript">
  var rb_purchased = $("#purchased");
  var rb_unpurchased = $("#unpurchased");
  var field = $("#purchased_at");

  console.log(field);

  var changePurchasedAt = function() {
    if (rb_purchased.prop("checked"))
      field.show()
    else
      field.hide()
  }

  var changeUnpurchasedAt = function() {
    if (rb_unpurchased.prop("checked"))
      field.hide()
    else
      field.show()
  }

  rb_purchased.bind("click", changePurchasedAt);
  rb_unpurchased.bind("click", changeUnpurchasedAt);

  changePurchasedAt();
  changeUnpurchasedAt();
</script>

<script type="text/javascript">
  $('#post_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('5MBより小さいファイルを選択してください');
    }
  });
</script>

app/views/posts/search.html.erb
<% provide(:title, "検索結果") %>

<div class="container-fluid">
  <h3><%= "' #{params[:q]} 'の検索結果" %></h3>

  <% if user_signed_in? %>
    <%= link_to "新規投稿を作成", new_post_path, class: "btn btn-lg btn-primary" %>
  <% end %>

  <div><%= link_to "投稿一覧へ", posts_path %></div>
  <div><%= link_to "未購入一覧へ", unpurchases_path %></div>
  <div><%= link_to "購入済一覧へ", purchases_path %></div><br />

  <%= render 'shared/posts', posts: @posts %>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.name) %>

<div class="jumbotron jumbotron-fluid">
  <div class="container-fluid">
    <h3>
      <%= gravatar_for @post.user %>
      <%= link_to @post.user.name, user_path(@post.user) %>
    </h3>
    <% if @post.user == current_user %>
      <div><%= link_to "編集", edit_post_path(@post), class: "btn btn-lg btn-primary btn-block" %></div><br />
    <% end %>

    <div class="product-wrap">
      <div class="card">
        <div class="card-header">
          商品名
        </div>
        <div class="card-body">
          <h4 class="card-title"><%= @post.name %></h4>
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          商品説明
        </div>
        <div class="card-body">
          <p class="card-text"><%= @post.description %></p>
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          値段
        </div>
        <div class="card-body">
          <% if @post.price %>
            <p class="card-text"><%= @post.price %>円</p>
          <% end %>
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          購入状態
        </div>
        <div class="card-body">
          <% if @post.purchased == false %>
            <p class="card-text">未購入</p>
          <% else %>
            <p class="card-text">購入済</p>
          <% end %>
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          購入日
        </div>
        <div class="card-body">
          <% if @post.purchased_at %>
            <p class="card-text"><%= @post.purchased_at.strftime("%Y/%m/%d") %></p>
          <% end %>
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          公開設定
        </div>
        <div class="card-body">
          <% if @post.published == false %>
            <p class="card-text">非公開</p>
          <% else %>
            <p class="card-text">公開</p>
          <% end %>
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          投稿日
        </div>
        <div class="card-body">
          <p class="card-text"><%= @post.created_at.strftime("%Y/%m/%d") %></p>
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          写真
        </div>
        <div class="card-body">
          <p class="card-text">
            <%= image_tag @post.picture.url if @post.picture? %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/timeline.html.erb
<% provide(:title, "#{current_user.name}さんのタイムライン") %>

<div class="container-fluid">
  <h3><%= "#{current_user.name}さんのタイムライン" %></h3>

  <% if @feed_items.present? %>
    <p>
      <span class="green" style="color:#abd700;">緑:未購入</span><br>
      <span class="red" style="color:#ffab6b;">赤:購入済</span>
    </p>
  <% end %>

  <%= render 'shared/posts', posts: @feed_items %>
</div>